FROM wordpress

# Install NodeJS and NPM to build plugins
RUN apt-get update && apt-get install -y gnupg
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs npm

# Add Xdebug extension for PHP debugging
RUN pecl install xdebug-2.6.1 && docker-php-ext-enable xdebug
